#!/bin/bash

###
# Author: Thomas Chamberlin
#
# log: Log the given command both to the console and to disk, with separate
#      files for stdout and stderr
#
# usage:
#   log cmd
###


# If we have a failure in our pipe, return the error code for the failed
# command, not of this function
set -o pipefail
# Execute cleanup when program exits, under whatever conditions that may be
trap cleanup EXIT

cleanup() {
    if [ -f "$time_output" ]; then
        rm "$time_output"
    fi
}


# Check that there is at least one argument given
if [[ $# -eq 0 ]]; then
    echo "usage: $(basename "$0") command" >&2
    exit 1
fi

# Get the current time in a pretty format
now() {
    date +"%T.%3N"
}



start="$(now)"
/usr/bin/time --portability -- "$@" \
# Save the return value of `time` (which is the return value from the _actual_ command)
cmd_ret_val=$?
end="$(now)"

if [[ $cmd_ret_val -eq 0 ]]; then
    status="SUCCESS"
else
    status="FAILURE"
fi
echo "${status}: ${start} to ${end}" >&2

# Alert based on the given command and its return code

# Return the value of the user's command
exit $cmd_ret_val
