#!/bin/bash

###
# Author: Thomas Chamberlin
#
# rmlog: Removes directories created by log.
#
# usage:
#   rmlog [path]
###


# Gives access to prompt
source bash_utils.sh

if [ -n "$1" ]; then
    path="$1"
else
    path=.
fi

log_dir_glob="*__*-*-*_*:*:*__logs"
log_file_pattern="(combined|stdout|stderr)\.log"

log_dirs=$(find "$path" -name "$log_dir_glob" -type d)

for dir in $log_dirs; do
    non_log_files=$(find "$dir" -mindepth 1 | grep -vE "$log_file_pattern")
    if [ -n "$non_log_files" ]; then
        non_log_files_found=true
        echo "$non_log_files"
    fi
done

if [ -n "$non_log_files_found" ]; then
    log_warning "The above files were not created by log! They will be deleted if you continue!"
fi

if [ -z "$log_dirs" ]; then
    log_warning "No log directories found in '$path'!"
    exit 0
fi

log_info "The following directories (and ALL of their contents) will be deleted: "
echo "$log_dirs"

prompt "Continue?"

for log_dir in $log_dirs; do
    rm --recursive --verbose --force -- "$log_dir"
done
