#!/bin/bash

source bash_utils.sh

if [ -n "$1" ]; then
    path="$1"
else
    path=.
fi

log_dir_glob="*__*-*-*_*:*:*__logs"
log_file_pattern="(combined|stdout|stderr)\.log"

log_dirs=$(find "$path" -name "$log_dir_glob" -type d)

for dir in $log_dirs; do
    non_log_files=$(find "$dir" -mindepth 1 | grep -vE "$log_file_pattern")
    if [ -n "$non_log_files" ]; then
        non_log_files_found=true
        for file in $non_log_files; do
            echo "  $file"
        done
    fi
done

if [ -n "$non_log_files_found" ]; then
    echo "WARNING: The above files were not created by log! They will be deleted if you continue!" >&2
fi

if [ -z "$log_dirs" ]; then
    echo "No log directories found in '$path'!"
    exit 0
fi

echo "The following directories (and ALL of their contents) will be deleted: "
for file in $log_dirs; do
    echo "  $file"
done

prompt "Continue?"

rm -rf "$log_dirs"
