#!/bin/bash

lcl() {
    local original_host; original_host=$(who am i | awk '{print $5}' | tr -d '()')
    if host "$original_host" &> /dev/null; then
        # shellcheck disable=SC2029
        echo "ORIGINAL HOST: $original_host"
        ssh -q "$original_host" "cd $(pwd); $*" &
    else
        "$@" &
    fi
}

failure_sound=/usr/share/sounds/k3b_error1.wav
success_sound=/usr/share/sounds/k3b_success1.wav

echo "Please enter a happy face: "
read -r result
if echo "$result" | grep -Eq '[:;]-?[])Dp]'; then
    success=true
fi

if [ -n "$success" ]; then
    sound=$success_sound
else
    sound=$failure_sound
fi

if [ -f "$sound" ]; then
    lcl aplay $sound &> /dev/null
fi
